### ISSUE TITLE
OOOPS!!! :( ERROR everywhere

### ISSUE THREAD

**Issue by ajaybhargav** [ajdeveloped/plugin.video.tvondesizonexl#2]
Plugin loads fine, lists all the shows properly. But when I click on a show and then click on aired date. It gives OOOPS!!! error. I checked many shows and all gives the same error.

**Comment by mhawaldar** [comment]
I observed yesterday that desirulez started using new urls(tvnewz.net) for dailymotion and flash links. I managed to tweak dr_actions to parse these new urls in my local installation and it is showing dailymotion links.

**Comment by ajaybhargav** [comment]
well the strange thing about desirulez is.. they use same website to play video files from different hosts. and hosts are decided based on video id you pass in the link. si=<vid>

you can try it...

**Comment by ajaybhargav** [comment]
can you share patche you've applied? did you directly modify the py file?

**Comment by mhawaldar** [comment]
I directly modified the py file. In fact today I see an update came in which fixed the flash, playwire links only. That update did not fix dailymotion links. I can share my file in some time as soon as I reach home.

**Comment by ajaybhargav** [comment]
can you simply paste the changes here? I will reflect it in my source. else if you know how to use git then probably it will become easy for you to upload a patch and merge it.

**Comment by mhawaldar** [comment]
I've create a fork and committed my changes to it:

mhawaldar/plugin.video.tvondesizonexl/tvshows/dr_actions.py

**Comment by ajaybhargav** [comment]
You can send a pull request to AJ so he can add those changes to his source.

**Comment by mhawaldar** [comment]
I did that some time back. Pardon the delay as this is my first time using github.

**Comment by ajaybhargav** [comment]
No problem. Hey do you have any idea how to add new show to this? I am not too good at python. I want to see WWE in the list. I am a wrestling fan :D

**Comment by mhawaldar** [comment]
The WWE format is much different then the other channels on DR. I'll give it a try if I understand more about this plugins.

**Comment by jchirag0221** [comment]
Hi mhawaldar,

Can you please send me the fix for dailymotion? I have access to upload the changes. I will make the changes so that everyone can access the new links.


Also you can press menu or right click on computer to get the other links in case the default link fails or when you get "Ooops error"

**Comment by jchirag0221** [comment]
Hi mhawaldar,

I have fixed this. Now it will show dailymotion links from new websites.

**Comment by jchirag0221** [comment]
Dailymotion links now fixed for most of the shows. Opps error comes when the source is moved or deleted.. Right click on date and select a different source.
