### ISSUE TITLE
Feature Request: Remote Menu navigation

### ISSUE THREAD

**Issue by ajaybhargav** [ajdeveloped/plugin.video.tvondesizonexl#5]
1. I am using xbmc on a device where mouse is not connected all time. So there is no option to do right click on show links and access alternate links in the list. Is it possible to enable or use right navigation key of remote to open alternate links.

2. when alternate link window opens and I go back it goes to show list again and it takes time to load show links again. so can you make menu go back to show links when I click back button on alternate links?

Thanks for this great plugin!

**Comment by jchirag0221** [comment]
1.  Do you have menu button on remote. The menu buttong works the same way as right click ..


2. I will look into this issues. 


Sent on the go with Vodafone


-------- Original message --------
