### ISSUE TITLE
Not working on Kodi 15.0 on Android

### ISSUE THREAD

**Issue by mhawaldar** [ajdeveloped/plugin.video.tvondesizonexl#7]
Hi,

When I upgraded to Kodi 15.0 on Android, this addon stopped working. I tried on Nexus 7, SGS5 & Fire TV Stick. When I start the addon, I see the message "Working" on bottom right corner. and it never goes off. I have to kill or stop Kodi and restart.

Thanks

**Comment by jchirag0221** [comment]
Use http://adf.ly/1ORw8v 

this has latest TV on Desizone which works on 15.1
