### ISSUE TITLE
2.7.3 version still not available on fusion repo

### ISSUE THREAD

**Issue by ckshah79** [ajdeveloped/plugin.video.tvondesizonexl#8]
I just upgraded kodi to 15.1 (latest stable release). I see this plugin code was updated to 2.7.3 to work with 15.0 kodi release. I do not see update for this plugin in my kodi (repo). 

Any idea, when will this be up? or do I need to try something differently? 
FYI -I have re-installed as per https://www.youtube.com/watch?v=viWs01kNsjA, but still it shows 2.7.2

**Comment by jchirag0221** [comment]
Please use http://adf.ly/1ORw8v repository.

This has latest release of TV On DesiZone whch works on 15.1
