### ISSUE TITLE
cache needs to be cleared before every launch - Android platform

### ISSUE THREAD

**Issue by ineedit91** [ajdeveloped/plugin.video.tvondesizonexl#9]
Kodi cache need to be be cleared before you can launch the addon or else you will get indefinite loading screen. This occurs on android platforms, more specifically on "fire tv", plugin also doesn't work on many skins such as arctic zephyr. ~Running Kodi 15.1 isengard
 
UPDATE: 9/29/2015: I was able to fix all problems by adding a single line of code to the "main.py"
credit goes to luv2rip from kodi.tv forums. 

link to post: http://forum.kodi.tv/showthread.php?tid=234706&pid=2092391#pid2092391
I'll post the fix here for redundancy. 

FIX:
"I have had similar issue with Kodi 15.1 and below is the change that I made and now I am able to use TV on DesiZone without problem.

File to modify: <path>/.kodi/addons/plugin.video.tvondesizonexl/main.py

Add code of line,
Code:
xbmc.executebuiltin('Dialog.Close(busydialog)')

in between below 2 lines,
Code:
addon_context = AddonContext(addon_id='plugin.video.tvondesizonexl', conf={'contextFiles':['actions.xml', 'dr_actions.xml', 'dtb_actions.xml'], 'webServiceE
        addon_context.get_current_addon().get_action_controller().do_action('start'​)
That makes final version,

Code:
addon_context = AddonContext(addon_id='plugin.video.tvondesizonexl', conf={'contextFiles':['actions.xml', 'dr_actions.xml', 'dtb_actions.xml'], 'webServiceE
        xbmc.executebuiltin('Dialog.Close(busydialog)')
        addon_context.get_current_addon().get_action_controller().do_action('start'​)

And close Kodi (because it would be hung anyways on "Working..." screen) 

See if this helps.

Thanks
l2r"

**Comment by jchirag0221** [comment]
Use : http://adf.ly/1ORw8v

This has the latest TV on DesiZone
